PIQA-13 TEeget document
pagopa/interop-qa-tests pull request #17
Opened 2024-01-18 17:37 UTC by paolomanca-pagopa

2024-01-26 09:41 UTC, taglioni-r commented on features/catalog/step_definitions/document-read.ts
> +    this.response = await apiClient.eservices.deleteEServiceDocumentById(
We should fix this and add polling.

2024-01-29 16:37 UTC, ruggerocastagnola requested changes

2024-01-29 16:37 UTC, ruggerocastagnola commented on features/catalog/document-read.feature
> +  Scenario Outline: Per un e-service che ha un solo descrittore, il quale è in qualsiasi stato (DRAFT, PUBLISHED, SUSPENDED, DEPRECATED, ARCHIVED), alla richiesta di recupero di un documento preceden
Se lo stato è `DRAFT`, solo gli `admin` e gli `api` possono vedere. Su tutti gli altri stati, tutti possono vedere. Testare solo per la matrice GSP/PA. Aggiungere la colonna `risultato`

2024-01-29 16:37 UTC, ruggerocastagnola commented on features/catalog/document-read.feature
> +      | PA1            | admin |
Eliminare la matrice

2024-02-06 10:29 UTC, ruggerocastagnola requested changes

2024-02-06 10:29 UTC, ruggerocastagnola commented on features/catalog/document-read.feature
> +  Tutti gli utenti autenticati di enti erogatori possono recuperare un'interfaccia o un documento dai propri descrittori
Rimuovere `di enti erogatori`

2024-02-06 10:29 UTC, ruggerocastagnola commented on features/catalog/document-read.feature
> +    Given un "admin" di "<ente>" ha già creato un e-service con un descrittore in stato "<statoDescrittore>" e un documento già caricato
Invece di `"<ente>"`, mettere `PA1`

2024-02-06 10:34 UTC, ruggerocastagnola approved these changes

2024-02-06 10:34 UTC, merged